### ISSUE TITLE
handle installation instructions not clear enough 

### ISSUE THREAD

**Issue by cookie33** [pidconsortium/EPIC-API-v2#2]
A client installed a new handle server from scratch. The `config.dct` contained following:

```
    "server_admins" = (
      "300:0.NA/<prefix>"
    )

    "replication_admins" = (
      "300:0.NA/<prefix>"
    )

    "backup_admins" = (
      "300:0.NA/<prefix>"
    )
```

The prefix was the same in every instance. This caused some problems. The customer was NOT able to home the prefix among other things.

The section about the handle server needs to be extended with info about this. An example config would be:

```
    "server_admins" = (
      "300:0.NA/<prefix>"
    )

    "replication_admins" = (
      "301:0.NA/<prefix>"
    )

    "backup_admins" = (
      "310:0.NA/<prefix>"
    )
```

**Comment by tkalman** [comment]
"The _prefix_ was the same in every instance." 
I believe you are mentioning the 'index', so "The **index** was the same".

**Comment by cookie33** [comment]
Hi,

Both index and prefix where the same in the config.dct.

The index being the same caused the problem.

**Comment by cookie33** [comment]
This comment is fixed..

close
