### ISSUE TITLE
The README.md mentions CatchPlus instead of pidconsortium

### ISSUE THREAD

**Issue by cookie33** [pidconsortium/EPIC-API-v2#3]
The README.md mentions CatchPlus in paths, while this active fork is pidconsortium.

The README.md needs to be adapted for this. Otherwise f.i. code from CatchPlus is downloaded and NOT pidconsortium.

**Comment by cookie33** [comment]
IT is in the following files that it mentions CatchPlus:

```
EPIC-API-v2$ grep -ri CatchPlus * | sort
EPIC.md:[here](http://catchplus.github.com/EPIC-API-v2/).
README.md:*   [as a zipfile](https://github.com/CatchPlus/EPIC-API-v2/zipball/gh-pages)
README.md:*   [as a zipfile](https://github.com/CatchPlus/EPIC-API-v2/zipball/master)
README.md:*   or [as a tarball](https://github.com/CatchPlus/EPIC-API-v2/tarball/gh-pages)
README.md:*   or [as a tarball](https://github.com/CatchPlus/EPIC-API-v2/tarball/master)
README.md:* git clone git://github.com/CatchPlus/EPIC-API-v2.git
README.md:[here, as GitHub pages](http://catchplus.github.com/EPIC-API-v2/).
config.rb.example:  VERSION_URL='https://github.com/CatchPlus/EPIC-API-v2/issues?milestone=10&state=closed'
src/epic_resource.rb:  <a href="http://www.catchplus.nl/">CATCH+</a>,
```

I don't know if the last one has to be adapted.. But the others definitly.

**Comment by tkalman** [comment]
The pidconsortium/EPIC-API-v2 repository does not use github pages for the documentation, but the CatchPlusEPIC-API-v2 repository does (see [here, as GitHub pages](http://catchplus.github.com/EPIC-API-v2/)). However, the docu there has not been updated since 2012…
So changing the following is challenging:

```
EPIC-API-v2$ grep -ri CatchPlus * | sort
README.md:[here, as GitHub pages](http://catchplus.github.com/EPIC-API-v2/).
```

I was now updating this to the main repository URL.

**Comment by tkalman** [comment]
I don't know if this file is still needed (seems to be part of the github pages only, but pages are in the gh-pages branch):

```
EPIC-API-v2$ grep -ri CatchPlus * | sort
EPIC.md:[here](http://catchplus.github.com/EPIC-API-v2/).
```

I am now updating this to the main repository URL and http://doc.pidconsortium.eu .
